# Generated by Django 4.1.3 on 2023-02-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conf', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvirData',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(null=True, verbose_name='环境配置项')),
                ('envir', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pro_data_envir', to='conf.confenvir', verbose_name='关联环境')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'project_envir_data',
                'unique_together': {('envir', 'project')},
            },
        ),
    ]
