# Generated by Django 4.1.3 on 2023-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfExpectRule',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('position', models.SmallIntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '期望判断规则表',
                'db_table': 'conf_expect_rule',
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='confenvir',
            options={'ordering': ('position',), 'verbose_name': '环境配置字典表'},
        ),
        migrations.AlterModelOptions(
            name='confparamtype',
            options={'ordering': ('position',), 'verbose_name': '参数类型表'},
        ),
    ]
