# Generated by Django 4.1.3 on 2023-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_confexpectrule_alter_confenvir_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confenvir',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
