# Generated by Django 4.1.3 on 2023-01-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_initial'),
        ('apiData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='测试用例名称')),
                ('status', models.IntegerField(default=0, verbose_name='执行结果')),
                ('remark', models.TextField(null=True, verbose_name='用例备注')),
                ('report_data', models.JSONField(null=True, verbose_name='测试报告数据')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否删除')),
                ('latest_run_time', models.DateTimeField(null=True, verbose_name='最后一次执行时间')),
            ],
            options={
                'verbose_name': '接口用例',
                'db_table': 'api_case',
            },
        ),
        migrations.CreateModel(
            name='ApiCaseModule',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('module_related', models.JSONField(default=[], verbose_name='所属模块级联关系（父子级）')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
            ],
            options={
                'verbose_name': '用例模块',
                'db_table': 'api_case_module',
            },
        ),
        migrations.CreateModel(
            name='ApiCaseStep',
            fields=[
                ('step_name', models.CharField(default='', max_length=255, verbose_name='步骤名称')),
                ('type', models.CharField(default='case', max_length=255, verbose_name='执行参数类型(1.api2.case；3.SQL 4.header（取value） 5.var 6.host)')),
                ('status', models.IntegerField(default=0, verbose_name='执行状态')),
                ('params', models.JSONField(null=True, verbose_name='步骤参数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('controller_data', models.JSONField(null=True, verbose_name='步骤控制器')),
                ('retried_times', models.SmallIntegerField(null=True, verbose_name='重试了几次')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('results', models.JSONField(null=True, verbose_name='步骤执行结果')),
            ],
            options={
                'verbose_name': 'api用例的步骤',
                'db_table': 'api_case_step',
            },
        ),
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='接口名称')),
                ('path', models.CharField(max_length=255, verbose_name='接口地址')),
                ('method', models.CharField(max_length=16, verbose_name='请求方法')),
                ('status', models.IntegerField(default=0, verbose_name='执行结果')),
                ('default_params', models.JSONField(null=True, verbose_name='默认参数')),
                ('timeout', models.SmallIntegerField(null=True, verbose_name='接口请求超时时间')),
                ('source', models.SmallIntegerField(default=1, verbose_name='接口来源')),
            ],
            options={
                'verbose_name': 'api用例',
                'db_table': 'api_data',
            },
        ),
        migrations.CreateModel(
            name='ApiModule',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('module_related', models.JSONField(default=[], verbose_name='所属模块级联关系（父子级）')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiData.apimodule', verbose_name='父模块')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '用例模块',
                'db_table': 'api_module',
            },
        ),
        migrations.CreateModel(
            name='ApiForeachStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(default='', max_length=255, verbose_name='步骤名称')),
                ('type', models.CharField(default='case', max_length=255, verbose_name='执行参数类型(1.api2.case；3.SQL 4.header（取value） 5.var 6.host)')),
                ('status', models.IntegerField(default=0, verbose_name='执行状态')),
                ('params', models.JSONField(null=True, verbose_name='步骤参数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('controller_data', models.JSONField(null=True, verbose_name='步骤控制器')),
                ('retried_times', models.SmallIntegerField(null=True, verbose_name='重试了几次')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apiData.apidata', verbose_name='步骤使用了的接口')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiData.apiforeachstep', verbose_name='父循环步骤')),
                ('quote_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_quote_case', to='apiData.apicase', verbose_name='引用的测试用例')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiData.apicasestep', verbose_name='所属测试用例')),
            ],
            options={
                'verbose_name': 'api用例的步骤',
                'db_table': 'api_foreach_step',
            },
        ),
    ]
