# Generated by Django 4.1.3 on 2023-02-22 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiData', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='apidata',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apiData.apimodule', verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='apidata',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apidata',
            name='updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_upd_user', to=settings.AUTH_USER_MODEL, verbose_name='修改用户'),
        ),
        migrations.AddField(
            model_name='apicasestep',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apiData.apidata', verbose_name='步骤使用了的接口'),
        ),
        migrations.AddField(
            model_name='apicasestep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_step', to='apiData.apicase', verbose_name='所属测试用例'),
        ),
        migrations.AddField(
            model_name='apicasestep',
            name='quote_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_quote_case', to='apiData.apicase', verbose_name='引用的测试用例'),
        ),
        migrations.AddField(
            model_name='apicasemodule',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiData.apicasemodule', verbose_name='父模块'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiData.apicasemodule', verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='apicase',
            name='updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_upd_user', to=settings.AUTH_USER_MODEL, verbose_name='修改用户'),
        ),
        migrations.AlterUniqueTogether(
            name='apidata',
            unique_together={('project', 'path', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='apicase',
            unique_together={('name', 'module')},
        ),
    ]
